# Generated by Django 4.2.6 on 2023-10-28 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
    ]
