# Generated by Django 4.2.6 on 2023-10-29 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='woreda',
            table='woreda',
        ),
    ]
