# Generated by Django 4.2.6 on 2023-10-29 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_woreda_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='woreda',
            options={'managed': False},
        ),
    ]
