# Generated by Django 4.2.6 on 2023-10-29 02:20

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_alter_incidences_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='')),
                ('geom', djgeojson.fields.GeometryCollectionField()),
            ],
        ),
        migrations.DeleteModel(
            name='Incidences',
        ),
        migrations.DeleteModel(
            name='Woredas',
        ),
    ]
